<testsuite name="Mocha Tests" tests="3" failures="2" errors="2" skipped="0" timestamp="Tue, 16 Jul 2013 20:07:37 GMT" time="0.017">
<testcase classname="User Tests Basic functions" name="should be the &quot;chris&quot; User" time="NaN" message="failed to connect to [localhost:27017]"><failure classname="User Tests Basic functions" name="should be the &quot;chris&quot; User" time="NaN" message="failed to connect to [localhost:27017]"><![CDATA[Error: failed to connect to [localhost:27017]
    at null.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:604:74)
    at EventEmitter.emit (events.js:106:17)
    at null.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:139:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:476:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)]]></failure></testcase>
<testcase classname="User Tests Basic functions" name="should have a create function" time="0" message="failed to connect to [localhost:27017]"><failure classname="User Tests Basic functions" name="should have a create function" time="0" message="failed to connect to [localhost:27017]"><![CDATA[Error: failed to connect to [localhost:27017]
    at null.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:604:74)
    at EventEmitter.emit (events.js:106:17)
    at null.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:139:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:476:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)]]></failure></testcase>
<testcase classname="User Tests Basic functions" name="should have a create function" time="0" message="failed to connect to [localhost:27017]"><failure classname="User Tests Basic functions" name="should have a create function" time="0" message="failed to connect to [localhost:27017]"><![CDATA[Error: failed to connect to [localhost:27017]
    at null.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:604:74)
    at EventEmitter.emit (events.js:106:17)
    at null.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:139:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.&lt;anonymous&gt; (/home/appsfactory/Factory/Horizon/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:476:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)]]></failure></testcase>
</testsuite>
